// =================================================================
// [AGENTE 01 — Legal & Compliance] Contenido Legal Centralizado
// Cumplimiento: Ley 19.628 (Chile) · GDPR (UE) · Principios HIPAA
// Versión: 1.0 — 2026-04-02
// =================================================================

/**
 * Versión de los términos legales vigentes.
 * Al incrementar este valor (ej. "1.1.0") todos los usuarios existentes
 * serán redirigidos al onboarding para re-aceptar los términos actualizados.
 * Incrementar MAJOR para cambios sustanciales (política de privacidad, nuevos
 * usos de datos). MINOR para aclaraciones. PATCH para correcciones menores.
 */
const LEGAL_VERSION = "1.0.0";

const legalContent = {
  es: {
    consentSectionTitle: "Consentimiento Informado",

    disclaimerTitle: "⚕️ Aviso Médico Importante",
    disclaimerText:
      "Nura es una herramienta de apoyo informativo y nutricional. " +
      "La información, recomendaciones y alertas generadas por esta aplicación " +
      "—incluyendo las asistidas por inteligencia artificial— NO constituyen " +
      "consejo médico, diagnóstico clínico ni prescripción de tratamiento. " +
      "Siempre consulta a un profesional de la salud calificado antes de tomar " +
      "cualquier decisión relacionada con tu salud. " +
      "En caso de emergencia médica, contacta de inmediato los servicios de " +
      "urgencia de tu localidad.",

    privacyTitle: "🔒 Política de Privacidad",
    privacyText:
      "De acuerdo con la Ley N° 19.628 sobre Protección de la Vida Privada " +
      "(Chile) y los principios del Reglamento General de Protección de Datos " +
      "(GDPR, UE):\n\n" +
      "• Responsable del tratamiento: Nura App " +
      "(Contacto: privacidad@nura-app.com).\n" +
      "• Edad mínima: Esta aplicación está dirigida exclusivamente a mayores de " +
      "18 años. Si eres menor de edad, no debes registrarte.\n" +
      "• Datos recopilados: datos de salud (peso, talla, patología crónica) y " +
      "medicamentos registrados.\n" +
      "• Finalidad: personalizar tu experiencia nutricional y generar alertas de " +
      "interacción fármaco-alimento.\n" +
      "• Base legal: consentimiento explícito del titular (Art. 13, Ley 19.628).\n" +
      "• Terceros y transferencia internacional: utilizamos Firebase (Google LLC) " +
      "para autenticación y almacenamiento en la nube. Tus datos pueden ser " +
      "transferidos a servidores seguros ubicados fuera de Chile, bajo protocolos " +
      "de seguridad certificados (ISO 27001).\n" +
      "• Seguridad: tus datos se cifran con AES-GCM 256-bit en reposo y se " +
      "transmiten sobre HTTPS con autenticación Firebase.\n" +
      "• Conservación: tus datos se conservan mientras tu cuenta esté activa y " +
      "son eliminados definitivamente 30 días después de solicitar la baja.\n" +
      "• Derechos: tienes derecho de acceso, rectificación, cancelación y " +
      "oposición. Contáctanos en privacidad@nura-app.com.",

    aiTitle: "🤖 Uso de Datos para Investigación y Desarrollo de IA",
    aiText:
      "Si otorgas este consentimiento opcional, tus datos de salud serán " +
      "sometidos a un proceso de anonimización irreversible —eliminando nombre, " +
      "correo electrónico, UID y cualquier identificador personal— antes de ser " +
      "incorporados a conjuntos de datos de entrenamiento del modelo de " +
      "inteligencia artificial de Nura.\n\n" +
      "Este proceso cumple con los estándares ISO/IEC 29101 y los principios de " +
      "minimización de datos del GDPR. Tu participación es completamente " +
      "voluntaria; puedes retirar este consentimiento en cualquier momento desde " +
      "la configuración de tu cuenta, sin que ello afecte el uso normal de la " +
      "aplicación.",

    consentTermsLabel:
      "He leído y acepto el Aviso Médico y la Política de Privacidad. " +
      "(Obligatorio)",
    consentAiLabel:
      "Acepto que mis datos, una vez anonimizados de forma irreversible, sean " +
      "utilizados para mejorar el modelo de IA de Nura. (Opcional)",

    readMore: "Leer más ▾",
    readLess: "Leer menos ▴",

    errorTermsRequired:
      "Debes aceptar el Aviso Médico y la Política de Privacidad para continuar."
  },

  en: {
    consentSectionTitle: "Informed Consent",

    disclaimerTitle: "⚕️ Important Medical Disclaimer",
    disclaimerText:
      "Nura is an informational and nutritional support tool. " +
      "The information, recommendations, and alerts generated by this application " +
      "— including those assisted by artificial intelligence — do NOT constitute " +
      "medical advice, clinical diagnosis, or treatment prescription. " +
      "Always consult a qualified healthcare professional before making any " +
      "health-related decision. " +
      "In case of a medical emergency, contact your local emergency services " +
      "immediately.",

    privacyTitle: "🔒 Privacy Policy",
    privacyText:
      "In accordance with Chile's Law No. 19.628 on Protection of Private Life " +
      "and the principles of the General Data Protection Regulation (GDPR, EU):\n\n" +
      "• Data controller: Nura App " +
      "(Contact: privacidad@nura-app.com).\n" +
      "• Minimum age: This application is intended exclusively for users aged " +
      "18 and over. If you are a minor, you must not register.\n" +
      "• Data collected: health data (weight, height, chronic pathology) and " +
      "registered medications.\n" +
      "• Purpose: to personalize your nutritional experience and generate " +
      "drug-food interaction alerts.\n" +
      "• Legal basis: explicit consent of the data subject (Art. 13, Law 19.628).\n" +
      "• Third parties and international transfers: we use Firebase (Google LLC) " +
      "for authentication and cloud storage. Your data may be transferred to " +
      "secure servers located outside Chile, under certified security protocols " +
      "(ISO 27001).\n" +
      "• Security: your data is encrypted with AES-GCM 256-bit at rest and " +
      "transmitted over HTTPS with Firebase authentication.\n" +
      "• Retention: your data is retained while your account is active and " +
      "permanently deleted 30 days after you request account closure.\n" +
      "• Rights: you have the right of access, rectification, cancellation, and " +
      "objection. Contact us at privacidad@nura-app.com.",

    aiTitle: "🤖 Use of Data for AI Research & Development",
    aiText:
      "If you grant this optional consent, your health data will undergo an " +
      "irreversible anonymization process — removing name, email, UID, and any " +
      "personal identifier — before being incorporated into Nura's AI model " +
      "training datasets.\n\n" +
      "This process complies with ISO/IEC 29101 standards and GDPR data " +
      "minimization principles. Your participation is completely voluntary; " +
      "you may withdraw this consent at any time from your account settings, " +
      "without affecting your normal use of the application.",

    consentTermsLabel:
      "I have read and accept the Medical Disclaimer and the Privacy Policy. " +
      "(Required)",
    consentAiLabel:
      "I consent to my data being irreversibly anonymized and used to improve " +
      "Nura's AI model. (Optional)",

    readMore: "Read more ▾",
    readLess: "Read less ▴",

    errorTermsRequired:
      "You must accept the Medical Disclaimer and Privacy Policy to continue."
  }
};
